apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodebinding-webhook-deployment
  namespace: nodebinding
  labels:
    app: nodebinding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodebinding
  template:
    metadata:
      labels:
        app: nodebinding
    spec:
      serviceAccountName: nodebinding-service-account
      containers:
        - name: nodebinding
          image: xpacrdemo.azurecr.io/nodebinding:latest
          imagePullPolicy: IfNotPresent
          args:
          - -tlsCertFile=/etc/webhook/certs/cert.pem
          - -tlsKeyFile=/etc/webhook/certs/key.pem
          - -alsologtostderr
          - -v=4
          - 2>&1
          volumeMounts:
          - name: webhook-certs
            mountPath: /etc/webhook/certs
            readOnly: true
      volumes:
      - name: webhook-certs
        secret:
          secretName: nodebinding-webhook-certs
